name: mfk_sensor
description: A Flutter app for collecting sensor data from SEN55/SEN66 devices
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.36.8
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_local_notifications: ^16.3.0  # Ez a helyes csomagnÃ©v!
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  supabase_flutter: ^2.10.2
  intl: ^0.20.2
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  webview_flutter: ^4.9.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
        - assets/images/mfk_logo.png
        - assets/images/emnl_logo.png
